version: "3.4"
services:
  ipfs:
    image: lscr.io/linuxserver/ipfs
    container_name: ipfs-2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
    ports:
      - 8085:80
      - 4001:4001
      - 5001:5001
      - 8080:8080
      - 443:443 #optional
    restart: unless-stopped